### ISSUE TITLE
Solder mod

### ISSUE THREAD

**Issue by waraileron** [danjperron/ESP12EMotorShieldRollerBlind#2]
Hi is solder mod on motor shield needed for this code fork?

**Comment by danjperron** [comment]
No . I made the change on the code to use the PWM and the direction.

Check the Jpeg picture! It shows how the shield works! 

You could use my  'C' version which  has better debouncing for the button. Also the buttons has  down,stop,up,stop cycle when it's not in calibration mode.

Be aware that the wiring is different  A-,A+  is one coil  and B-,B+ is the other coil.  If you have a 4 wires stepper you don't need to connect the center tap but for the 28BYJ48 stepper you need to connect the red wire to the Vmotor.  Check my code remarks, the colors of the wires are described.

**Comment by waraileron** [comment]
Thanks! I have read through the codes and tested continuity hence have closed the issue. I wish I didnt try to do the mod and screw up the board, now I'll have to wait for a second board to arrive before testing.

Cheers!
